# Generated by Django 3.0 on 2019-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kosdaq_StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kospi_StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Pair_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Base_stock', models.CharField(max_length=20)),
                ('Pair_stock', models.CharField(max_length=20)),
                ('Cash_Balance', models.IntegerField(default=0)),
                ('Count1', models.IntegerField(default=0)),
                ('Count2', models.IntegerField(default=0)),
                ('Avg_price1', models.IntegerField(default=0)),
                ('Avg_price2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField()),
                ('Stock_Name1', models.CharField(max_length=50)),
                ('Stock_Name2', models.CharField(max_length=50)),
                ('Signal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Target_StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
            ],
        ),
    ]
